[2023-01-06T14:43:34.668+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.remove_dl_config_cfg_from_s3 manual__2023-01-06T13:21:32.663212+00:00 [queued]>
[2023-01-06T14:43:34.684+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.remove_dl_config_cfg_from_s3 manual__2023-01-06T13:21:32.663212+00:00 [queued]>
[2023-01-06T14:43:34.685+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T14:43:34.685+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T14:43:34.685+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T14:43:34.699+0000] {taskinstance.py:1389} INFO - Executing <Task(S3DeleteObjectsOperator): remove_dl_config_cfg_from_s3> on 2023-01-06 13:21:32.663212+00:00
[2023-01-06T14:43:34.704+0000] {standard_task_runner.py:52} INFO - Started process 455 to run task
[2023-01-06T14:43:34.707+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_update_datalake', 'remove_dl_config_cfg_from_s3', 'manual__2023-01-06T13:21:32.663212+00:00', '--job-id', '3957', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/datalake_update.py', '--cfg-path', '/tmp/tmptpagof77', '--error-file', '/tmp/tmpyc5jrc0s']
[2023-01-06T14:43:34.708+0000] {standard_task_runner.py:80} INFO - Job 3957: Subtask remove_dl_config_cfg_from_s3
[2023-01-06T14:43:34.770+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_update_datalake.remove_dl_config_cfg_from_s3 manual__2023-01-06T13:21:32.663212+00:00 [running]> on host 370ed6868bc3
[2023-01-06T14:43:34.839+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_update_datalake
AIRFLOW_CTX_TASK_ID=remove_dl_config_cfg_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T13:21:32.663212+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T13:21:32.663212+00:00
[2023-01-06T14:43:34.850+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T14:43:34.851+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T14:43:35.705+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'atn-dl-data.s3.us-west-2.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2023-01-06T14:43:35.967+0000] {s3.py:847} INFO - Deleted: ['scripts/dl_config.cfg']
[2023-01-06T14:43:35.984+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_update_datalake, task_id=remove_dl_config_cfg_from_s3, execution_date=20230106T132132, start_date=20230106T144334, end_date=20230106T144335
[2023-01-06T14:43:36.010+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T14:43:36.049+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
