[2023-01-06T12:31:34.468+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:31:34.484+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:31:34.484+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:31:34.484+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 3
[2023-01-06T12:31:34.484+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:31:34.498+0000] {taskinstance.py:1389} INFO - Executing <Task(EmrTerminateJobFlowOperator): end_emr_cluster> on 2023-01-06 00:00:00+00:00
[2023-01-06T12:31:34.502+0000] {standard_task_runner.py:52} INFO - Started process 102 to run task
[2023-01-06T12:31:34.506+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'end_emr_cluster', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3824', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmpq9rlorj1', '--error-file', '/tmp/tmpxxf9rfcv']
[2023-01-06T12:31:34.506+0000] {standard_task_runner.py:80} INFO - Job 3824: Subtask end_emr_cluster
[2023-01-06T12:31:34.522+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T12:31:34.578+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T12:31:34.664+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=end_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T12:31:34.676+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T12:31:34.677+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T12:31:34.736+0000] {emr.py:410} INFO - Terminating JobFlow None
[2023-01-06T12:31:36.231+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 411, in execute
    response = emr.terminate_job_flows(JobFlowIds=[self.job_flow_id])
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the TerminateJobFlows operation: Specified job flow ID not valid.
[2023-01-06T12:31:36.254+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=atn_import_data_from_apis, task_id=end_emr_cluster, execution_date=20230106T000000, start_date=20230106T123134, end_date=20230106T123136
[2023-01-06T12:31:36.270+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3824 for task end_emr_cluster (An error occurred (ValidationException) when calling the TerminateJobFlows operation: Specified job flow ID not valid.; 102)
[2023-01-06T12:31:36.297+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-06T12:31:36.338+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
