[2023-01-08T16:25:46.406+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.remove_dl_config_cfg_from_s3 manual__2023-01-08T15:06:09.206673+00:00 [queued]>
[2023-01-08T16:25:46.422+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.remove_dl_config_cfg_from_s3 manual__2023-01-08T15:06:09.206673+00:00 [queued]>
[2023-01-08T16:25:46.422+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T16:25:46.422+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-08T16:25:46.423+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T16:25:46.437+0000] {taskinstance.py:1389} INFO - Executing <Task(S3DeleteObjectsOperator): remove_dl_config_cfg_from_s3> on 2023-01-08 15:06:09.206673+00:00
[2023-01-08T16:25:46.442+0000] {standard_task_runner.py:52} INFO - Started process 409 to run task
[2023-01-08T16:25:46.445+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_update_datalake', 'remove_dl_config_cfg_from_s3', 'manual__2023-01-08T15:06:09.206673+00:00', '--job-id', '4093', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/datalake_update.py', '--cfg-path', '/tmp/tmp05g0ppzg', '--error-file', '/tmp/tmprl03jha3']
[2023-01-08T16:25:46.446+0000] {standard_task_runner.py:80} INFO - Job 4093: Subtask remove_dl_config_cfg_from_s3
[2023-01-08T16:25:46.512+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_update_datalake.remove_dl_config_cfg_from_s3 manual__2023-01-08T15:06:09.206673+00:00 [running]> on host 370ed6868bc3
[2023-01-08T16:25:46.581+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_update_datalake
AIRFLOW_CTX_TASK_ID=remove_dl_config_cfg_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T15:06:09.206673+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T15:06:09.206673+00:00
[2023-01-08T16:25:46.592+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-08T16:25:46.592+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-08T16:25:47.211+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'atn-dl-data.s3.us-west-2.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2023-01-08T16:25:47.417+0000] {s3.py:847} INFO - Deleted: ['scripts/dl_config.cfg']
[2023-01-08T16:25:47.457+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_update_datalake, task_id=remove_dl_config_cfg_from_s3, execution_date=20230108T150609, start_date=20230108T162546, end_date=20230108T162547
[2023-01-08T16:25:47.505+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-08T16:25:47.566+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
